### ISSUE TITLE
Cant install VMware Tools

### ISSUE THREAD

**Issue by Kolyall** [BroFox86/macos-plus#1]
Cant install VMware Tools
Error:
```
This operation cannot proceed because your Mac OS guest is using the CD/DVD.

Dismiss this message, eject the disc from inside the guest, and retry this operation.
```

**Comment by BroFox86** [comment]
1. Install latest VMWare Player (it was updated recently): [www.vmware.com/products/workstation-player](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html?ClickID=a5s5w9r5ta00lt990z0ys0plzsw95pvaystn)
2. Remove previous version of Unlocker (win-uninstall.cmd)
3. Download and install latest Unlocker here: [github.com/DrDonk/unlocker](https://github.com/DrDonk/unlocker/releases)
4. Try again.

**Comment by BroFox86** [comment]
The guide is updated. I close the issue.
