### ISSUE TITLE
Куда выводится результат работы gulp-w3cjs?

### ISSUE THREAD

**Issue by pustart** [BroFox86/macos-plus#2]
Привет! Установил себе плагин для gulp w3cjs, но я не понимаю куда он шлет репорты. В исходном репозитории gulp-w3cjs увидел ваше ишью с красивой картинкой о допущенной ошибке в html, у меня же такой ни в терминале, ни в вебтулзах не наблюдается. IDE - WebStorm. Может подскажете куда он выводит результат своей работы?

**Comment by BroFox86** [comment]
Привет. Результат выводится в терминал. Пример для Gulp 4:

<pre>
import w3cjs from "gulp-w3cjs";

export function validateHTML() {
  return src('temp/*.html')
     .pipe(w3cjs({ 
       showInfo: false 
      }))
     .pipe(w3cjs.reporter());
}
</pre>

<img width="500" alt="Снимок экрана 2021-11-25 в 18 27 05" src="https://user-images.githubusercontent.com/23554264/143467996-720dc0dd-86fa-4853-a5e9-4ca58c8207aa.png">

**Comment by pustart** [comment]
Спасибо за оперативную помощь! Как оказалось, у меня просто не было ошибок в html'е :D
